#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
Q8_DIRECTORY="$ROOT_DIR/artifacts/hibiki-1b-mlx-q8"
Q4_DIRECTORY="$ROOT_DIR/artifacts/hibiki-1b-mlx-q4"
cd "$ROOT_DIR"

# A non-interactive Bash process does not inherit Conda's shell function.
# Make the normal `conda run -n hibiki ...` command discoverable when this
# machine uses the standard Miniforge installation location.
if ! command -v conda >/dev/null 2>&1 && [[ -x "$HOME/miniforge3/bin/conda" ]]; then
  export PATH="$HOME/miniforge3/bin:$PATH"
fi

if ! command -v conda >/dev/null 2>&1; then
  warn "Conda was not found. Add Conda to PATH, then re-run this script."
  exit 1
fi

visibility_flag() {
  case "$1" in
    private) printf '%s' '--private' ;;
    public) printf '%s' '--public' ;;
    *)
      warn "visibility must be exactly private or public"
      return 1
      ;;
  esac
}

validate_visibility() {
  if [[ "$1" != "private" && "$1" != "public" ]]; then
    warn "visibility must be exactly private or public"
    exit 1
  fi
}

run_upload() {
  local directory="$1" repo_id="$2" visibility="$3"
  local visibility_option
  visibility_option=$(visibility_flag "$visibility")
  HF_TOKEN="$HF_TOKEN" conda run -n hibiki python -m hibiki_mlx.upload \
    "$directory" --repo-id "$repo_id" "$visibility_option"
}

run_dry_run() {
  local directory="$1" repo_id="$2" visibility="$3"
  local visibility_option
  visibility_option=$(visibility_flag "$visibility")
  HF_TOKEN="$HF_TOKEN" conda run -n hibiki python -m hibiki_mlx.upload \
    "$directory" --repo-id "$repo_id" "$visibility_option" --dry-run
}

banner "Publish Hibiki Q8 and Q4 artifacts"

stage "Create a Hugging Face write token"
say "The token is used only in this shell session and is never written to .env or the repository."
open_url "https://huggingface.co/settings/tokens"
step "Create a fine-grained token with write access to the two model repositories."
step "Copy the token, then paste it below."
ask_secret HF_TOKEN "Hugging Face write token:"
if [[ -z "$HF_TOKEN" ]]; then
  warn "a token is required to publish; stopping without uploading"
  exit 1
fi

stage "Choose the Q8 repository"
say "Suggested repository: anquachdev/hibiki-1b-mlx-q8"
ask Q8_REPO_ID "Q8 repository ID:"
ask Q8_VISIBILITY "Q8 visibility (private/public):"
validate_visibility "$Q8_VISIBILITY"

stage "Choose the Q4 repository"
say "Suggested repository: anquachdev/hibiki-1b-mlx-q4"
ask Q4_REPO_ID "Q4 repository ID:"
ask Q4_VISIBILITY "Q4 visibility (private/public):"
validate_visibility "$Q4_VISIBILITY"

stage "Validate and publish"
if [[ ! -d "$Q8_DIRECTORY" || ! -d "$Q4_DIRECTORY" ]]; then
  warn "quantized bundle directories are missing; run the Q8 and Q4 conversions first"
  exit 1
fi
say "First, the script validates both bundles without creating a repository or uploading files."
run_dry_run "$Q8_DIRECTORY" "$Q8_REPO_ID" "$Q8_VISIBILITY"
run_dry_run "$Q4_DIRECTORY" "$Q4_REPO_ID" "$Q4_VISIBILITY"
if confirm "Upload Q8 to $Q8_REPO_ID and Q4 to $Q4_REPO_ID now?"; then
  run_upload "$Q8_DIRECTORY" "$Q8_REPO_ID" "$Q8_VISIBILITY"
  run_upload "$Q4_DIRECTORY" "$Q4_REPO_ID" "$Q4_VISIBILITY"
else
  note "dry-run completed; no Hugging Face repository was created or modified"
fi

# ── Example stage: replace with your real steps ───────────────────────────
:
# ──────────────────────────────────────────────────────────────────────────

finish
